
export const supercrossRaces = [
  {
    round: 1,
    location: 'Anaheim, CA',
    date: 'Jan 10, 2026',
    track: 'Angel Stadium',
    tv: 'Peacock',
    ticketsUrl: '#',
    mapUrl: '#',
  },
  {
    round: 2,
    location: 'San Diego, CA',
    date: 'Jan 17, 2026',
    track: 'Snapdragon Stadium',
    tv: 'Peacock',
    ticketsUrl: '#',
    mapUrl: '#',
  },
  {
    round: 3,
    location: 'Anaheim, CA',
    date: 'Jan 24, 2026',
    track: 'Angel Stadium',
    tv: 'Peacock',
    ticketsUrl: '#',
    mapUrl: '#',
  },
  {
    round: 4,
    location: 'Houston, TX',
    date: 'Jan 31, 2026',
    track: 'NRG Stadium',
    tv: 'Peacock',
    ticketsUrl: '#',
    mapUrl: '#',
  },
  {
    round: 5,
    location: 'Glendale, AZ',
    date: 'Feb 07, 2026',
    track: 'State Farm Stadium',
    tv: 'Peacock',
    ticketsUrl: '#',
    mapUrl: '#',
  },
  {
    round: 6,
    location: 'Oakland, CA',
    date: 'Feb 14, 2026',
    track: 'RingCentral Coliseum',
    tv: 'Peacock',
    ticketsUrl: '#',
    mapUrl: '#',
  },
  {
    round: 7,
    location: 'Arlington, TX',
    date: 'Feb 21, 2026',
    track: 'AT&T Stadium',
    tv: 'Peacock',
    ticketsUrl: '#',
    mapUrl: '#',
    format: 'Triple Crown',
  },
  {
    round: 8,
    location: 'Daytona Beach, FL',
    date: 'Mar 01, 2026',
    track: 'Daytona International Speedway',
    tv: 'Peacock',
    ticketsUrl: '#',
    mapUrl: '#',
  },
];
