
export const supercrossRaces = [
  {
    round: 1,
    location: 'Anaheim, CA',
    date: 'Jan 10, 2026',
    track: 'Angel Stadium of Anaheim',
    tv: 'Peacock',
    division: 'West',
  },
  {
    round: 2,
    location: 'San Diego, CA',
    date: 'Jan 17, 2026',
    track: 'Snapdragon Stadium',
    tv: 'Peacock',
    division: 'West',
  },
  {
    round: 3,
    location: 'Anaheim, CA',
    date: 'Jan 24, 2026',
    track: 'Angel Stadium of Anaheim',
    tv: 'Peacock',
    division: 'West',
  },
  {
    round: 4,
    location: 'Houston, TX',
    date: 'Jan 31, 2026',
    track: 'NRG Stadium',
    tv: 'Peacock',
    division: 'West',
    format: 'Triple Crown',
  },
  {
    round: 5,
    location: 'Glendale, AZ',
    date: 'Feb 07, 2026',
    track: 'State Farm Stadium',
    tv: 'Peacock',
    division: 'West',
  },
  {
    round: 6,
    location: 'Seattle, WA',
    date: 'Feb 14, 2026',
    track: 'Lumen Field',
    tv: 'Peacock',
    division: 'West',
  },
  {
    round: 7,
    location: 'Arlington, TX',
    date: 'Feb 21, 2026',
    track: 'AT&T Stadium',
    tv: 'Peacock',
    division: 'East',
  },
  {
    round: 8,
    location: 'Daytona Beach, FL',
    date: 'Feb 28, 2026',
    track: 'Daytona International Speedway',
    tv: 'Peacock',
    division: 'East',
  },
  {
    round: 9,
    location: 'Indianapolis, IN',
    date: 'Mar 07, 2026',
    track: 'Lucas Oil Stadium',
    tv: 'Peacock',
    division: 'East',
    format: 'Triple Crown',
  },
  {
    round: 10,
    location: 'Birmingham, AL',
    date: 'Mar 21, 2026',
    track: 'Protective Stadium',
    tv: 'Peacock',
    division: 'East/West Showdown',
  },
  {
    round: 11,
    location: 'Detroit, MI',
    date: 'Mar 28, 2026',
    track: 'Ford Field',
    tv: 'Peacock',
    division: 'East',
  },
  {
    round: 12,
    location: 'St. Louis, MO',
    date: 'Apr 04, 2026',
    track: 'The Dome at America\'s Center',
    tv: 'Peacock',
    division: 'East/West Showdown',
  },
  {
    round: 13,
    location: 'Nashville, TN',
    date: 'Apr 11, 2026',
    track: 'Nissan Stadium',
    tv: 'Peacock',
    division: 'East',
  },
  {
    round: 14,
    location: 'Cleveland, OH',
    date: 'Apr 18, 2026',
    track: 'Huntington Bank Field',
    tv: 'Peacock',
    division: 'East',
    format: 'Triple Crown',
  },
  {
    round: 15,
    location: 'Philadelphia, PA',
    date: 'Apr 25, 2026',
    track: 'Lincoln Financial Field',
    tv: 'Peacock',
    division: 'East',
  },
  {
    round: 16,
    location: 'Denver, CO',
    date: 'May 02, 2026',
    track: 'Empower Field at Mile High',
    tv: 'Peacock',
    division: 'West',
  },
  {
    round: 17,
    location: 'Salt Lake City, UT',
    date: 'May 09, 2026',
    track: 'Rice-Eccles Stadium',
    tv: 'Peacock',
    division: 'East/West Showdown',
  },
];
