export const riders450 = [
    { id: 'aaron-plessinger', name: 'Aaron Plessinger', imageUrl: 'https://picsum.photos/seed/plessinger/400/400', imageHint: 'Aaron Plessinger portrait' },
    { id: 'adam-cianciarulo', name: 'Adam Cianciarulo', imageUrl: 'https://picsum.photos/seed/cianciarulo/400/400', imageHint: 'Adam Cianciarulo portrait' },
    { id: 'benny-bloss', name: 'Benny Bloss', imageUrl: 'https://picsum.photos/seed/bloss/400/400', imageHint: 'Benny Bloss portrait' },
    { id: 'chase-sexton', name: 'Chase Sexton', imageUrl: 'https://picsum.photos/seed/sexton/400/400', imageHint: 'Chase Sexton portrait' },
    { id: 'cooper-webb', name: 'Cooper Webb', imageUrl: 'https://picsum.photos/seed/webb/400/400', imageHint: 'Cooper Webb portrait' },
    { id: 'dean-wilson', name: 'Dean Wilson', imageUrl: 'https://picsum.photos/seed/wilson/400/400', imageHint: 'Dean Wilson portrait' },
    { id: 'dylan-ferrandis', name: 'Dylan Ferrandis', imageUrl: 'https://picsum.photos/seed/ferrandis/400/400', imageHint: 'Dylan Ferrandis portrait' },
    { id: 'eli-tomac', name: 'Eli Tomac', imageUrl: 'https://picsum.photos/seed/tomac/400/400', imageHint: 'Eli Tomac portrait' },
    { id: 'fredrik-noren', name: 'Fredrik Noren', imageUrl: 'https://picsum.photos/seed/noren/400/400', imageHint: 'Fredrik Noren portrait' },
    { id: 'grant-harlan', name: 'Grant Harlan', imageUrl: 'https://picsum.photos/seed/harlan/400/400', imageHint: 'Grant Harlan portrait' },
    { id: 'hunter-lawrence', name: 'Hunter Lawrence', imageUrl: 'https://picsum.photos/seed/hunter/400/400', imageHint: 'Hunter Lawrence portrait' },
    { id: 'jason-anderson', name: 'Jason Anderson', imageUrl: 'https://picsum.photos/seed/anderson/400/400', imageHint: 'Jason Anderson portrait' },
    { id: 'jett-lawrence', name: 'Jett Lawrence', imageUrl: 'https://picsum.photos/seed/jett/400/400', imageHint: 'Jett Lawrence portrait' },
    { id: 'justin-barcia', name: 'Justin Barcia', imageUrl: 'https://picsum.photos/seed/barcia/400/400', imageHint: 'Justin Barcia portrait' },
    { id: 'justin-cooper', name: 'Justin Cooper', imageUrl: 'https://picsum.photos/seed/jcooper/400/400', imageHint: 'Justin Cooper portrait' },
    { id: 'justin-hill', name: 'Justin Hill', imageUrl: 'https://picsum.photos/seed/jhill/400/400', imageHint: 'Justin Hill portrait' },
    { id: 'ken-roczen', name: 'Ken Roczen', imageUrl: 'https://picsum.photos/seed/roczen/400/400', imageHint: 'Ken Roczen portrait' },
    { id: 'malcolm-stewart', name: 'Malcolm Stewart', imageUrl: 'https://picsum.photos/seed/mstewart/400/400', imageHint: 'Malcolm Stewart portrait' },
    { id: 'shane-mcelrath', name: 'Shane McElrath', imageUrl: 'https://picsum.photos/seed/mcelrath/400/400', imageHint: 'Shane McElrath portrait' },
    { id: 'ty-masterpool', name: 'Ty Masterpool', imageUrl: 'https://picsum.photos/seed/masterpool/400/400', imageHint: 'Ty Masterpool portrait' },
  ];
