
export const states = [
  { name: 'Alabama', abbr: 'AL', minAge: 21 },
  { name: 'Alaska', abbr: 'AK', minAge: 18 },
  { name: 'Arizona', abbr: 'AZ', minAge: 18 },
  { name: 'Arkansas', abbr: 'AR', minAge: 18 },
  { name: 'California', abbr: 'CA', minAge: 18 },
  { name: 'Colorado', abbr: 'CO', minAge: 18 },
  { name: 'Connecticut', abbr: 'CT', minAge: 18 },
  { name: 'Delaware', abbr: 'DE', minAge: 18 },
  { name: 'Florida', abbr: 'FL', minAge: 18 },
  { name: 'Georgia', abbr: 'GA', minAge: 18 },
  { name: 'Hawaii', abbr: 'HI', minAge: 18 },
  { name: 'Idaho', abbr: 'ID', minAge: 18 },
  { name: 'Illinois', abbr: 'IL', minAge: 18 },
  { name: 'Indiana', abbr: 'IN', minAge: 18 },
  { name: 'Iowa', abbr: 'IA', minAge: 18 },
  { name: 'Kansas', abbr: 'KS', minAge: 18 },
  { name: 'Kentucky', abbr: 'KY', minAge: 18 },
  { name: 'Louisiana', abbr: 'LA', minAge: 18 },
  { name: 'Maine', abbr: 'ME', minAge: 18 },
  { name: 'Maryland', abbr: 'MD', minAge: 18 },
  { name: 'Massachusetts', abbr: 'MA', minAge: 18 },
  { name: 'Michigan', abbr: 'MI', minAge: 18 },
  { name: 'Minnesota', abbr: 'MN', minAge: 18 },
  { name: 'Mississippi', abbr: 'MS', minAge: 18 },
  { name: 'Missouri', abbr: 'MO', minAge: 18 },
  { name: 'Montana', abbr: 'MT', minAge: 18 },
  { name: 'Nebraska', abbr: 'NE', minAge: 21 },
  { name: 'Nevada', abbr: 'NV', minAge: 18 },
  { name: 'New Hampshire', abbr: 'NH', minAge: 18 },
  { name: 'New Jersey', abbr: 'NJ', minAge: 18 },
  { name: 'New Mexico', abbr: 'NM', minAge: 18 },
  { name: 'New York', abbr: 'NY', minAge: 18 },
  { name: 'North Carolina', abbr: 'NC', minAge: 18 },
  { name: 'North Dakota', abbr: 'ND', minAge: 18 },
  { name: 'Ohio', abbr: 'OH', minAge: 18 },
  { name: 'Oklahoma', abbr: 'OK', minAge: 18 },
  { name: 'Oregon', abbr: 'OR', minAge: 18 },
  { name: 'Pennsylvania', abbr: 'PA', minAge: 18 },
  { name: 'Rhode Island', abbr: 'RI', minAge: 18 },
  { name: 'South Carolina', abbr: 'SC', minAge: 18 },
  { name: 'South Dakota', abbr: 'SD', minAge: 18 },
  { name: 'Tennessee', abbr: 'TN', minAge: 18 },
  { name: 'Texas', abbr: 'TX', minAge: 18 },
  { name: 'Utah', abbr: 'UT', minAge: 18 },
  { name: 'Vermont', abbr: 'VT', minAge: 18 },
  { name: 'Virginia', abbr: 'VA', minAge: 18 },
  { name: 'Washington', abbr: 'WA', minAge: 18 },
  { name: 'West Virginia', abbr: 'WV', minAge: 18 },
  { name: 'Wisconsin', abbr: 'WI', minAge: 18 },
  { name: 'Wyoming', abbr: 'WY', minAge: 18 },
];
